import sys
import os
import time

# Adjust Python path to allow backend imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fastapi.testclient import TestClient
from backend.app import app
from backend.config import Config
from backend.database import get_db_connection

client = TestClient(app)

def setup_test_data():
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Insert a test case
    cursor.execute("INSERT INTO cases (title, description, status) VALUES ('Test Case Report', 'Report generation test case', 'Active')")
    case_id = cursor.lastrowid
    
    # Insert a test original
    cursor.execute("""
        INSERT INTO originals (case_id, filename, file_uuid, storage_provider, filesize, duration)
        VALUES (?, 'original_video.mp4', 'uuid-video-1234', 'local', 1024*1024, 10.5)
    """, (case_id,))
    
    # Insert a test evidence
    cursor.execute("""
        INSERT INTO evidence (case_id, platform, url, title, uploader, upload_date, similarity_score, status)
        VALUES (?, 'YouTube', 'https://www.youtube.com/watch?v=1234', 'Infringing Copy', 'uploader_john', '2026-07-04', 0.85, 'Detected')
    """, (case_id,))
    evidence_id = cursor.lastrowid
    
    conn.commit()
    conn.close()
    return case_id, evidence_id

def cleanup_test_data(case_id):
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM cases WHERE id = ?", (case_id,))
    conn.commit()
    conn.close()

def run_phase4_tests():
    print("--- Running Phase 4 Report Generator Tests ---")
    
    # Disable developer bypass
    old_bypass = Config.DEVELOPMENT_BYPASS_AUTH
    Config.DEVELOPMENT_BYPASS_AUTH = False
    
    case_id, evidence_id = setup_test_data()
    
    try:
        # 1. Login Admin to get token
        login_res = client.post("/api/v1/auth/login", json={"email": "admin", "password": "AdminPassword123"})
        assert login_res.status_code == 200, "Admin login failed"
        admin_token = login_res.json()["token"]
        
        # 2. Login a Guest user (we will register one first)
        guest_username = f"guest_{int(time.time())}"
        guest_email = f"{guest_username}@copyrightcenter.com"
        reg_res = client.post("/api/v1/auth/register", json={
            "username": guest_username,
            "email": guest_email,
            "password": "GuestPassword123",
            "role": "Guest"
        }, headers={"Authorization": f"Bearer {admin_token}"})
        assert reg_res.status_code == 201, f"Guest user registration failed: {reg_res.text}"
        
        guest_login = client.post("/api/v1/auth/login", json={"email": guest_username, "password": "GuestPassword123"})
        assert guest_login.status_code == 200, "Guest login failed"
        guest_token = guest_login.json()["token"]
        
        # 3. Test: Unauthenticated request to /generate is blocked (401)
        res = client.post("/api/v1/reports/generate", json={})
        assert res.status_code == 401, "Expected 401 Unauthorized"
        
        # 4. Test: Guest request to /generate is blocked (403)
        res = client.post("/api/v1/reports/generate", json={
            "case_id": case_id,
            "evidence_id": evidence_id,
            "sender_name": "Test Representative",
            "sender_email": "rep@copyright.com",
            "copyright_owner_name": "TSN Corp",
            "template_type": "youtube"
        }, headers={"Authorization": f"Bearer {guest_token}"})
        assert res.status_code == 403, f"Expected 403 Forbidden, got {res.status_code}"
        
        # 5. Test: Admin generates a draft report (200/201)
        # We also pass signature_base64
        dummy_signature = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="
        gen_res = client.post("/api/v1/reports/generate", json={
            "case_id": case_id,
            "evidence_id": evidence_id,
            "sender_name": "Test Representative",
            "sender_email": "rep@copyright.com",
            "sender_phone": "123-456-7890",
            "sender_address": "123 Main St, USA",
            "copyright_owner_name": "TSN Corp",
            "template_type": "youtube",
            "signature_base64": dummy_signature,
            "declaration_accepted": True
        }, headers={"Authorization": f"Bearer {admin_token}"})
        assert gen_res.status_code == 200, f"Report generation failed: {gen_res.text}"
        report = gen_res.json()
        report_id = report["id"]
        assert report["case_id"] == case_id
        assert report["status"] == "Signed"
        assert "YOUTUBE COPYRIGHT COMPLAINT NOTICE" in report["report_text"]
        print("OK: Report successfully generated by Admin with template and signature.")
        
        # 6. Test: Guest can read reports list
        list_res = client.get(f"/api/v1/reports/{case_id}", headers={"Authorization": f"Bearer {guest_token}"})
        assert list_res.status_code == 200, f"Expected 200, got {list_res.status_code}: {list_res.text}"
        reports_list = list_res.json()
        assert len(reports_list) > 0, "Reports list was empty"
        assert reports_list[0]["id"] == report_id, f"Expected report ID {report_id}, got {reports_list[0]['id']}"
        print("OK: Guest can read reports list.")
        
        # 7. Test: Guest can export PDF
        pdf_res = client.get(f"/api/v1/reports/{report_id}/export/pdf", headers={"Authorization": f"Bearer {guest_token}"})
        assert pdf_res.status_code == 200
        assert pdf_res.headers["content-type"] == "application/pdf"
        assert len(pdf_res.content) > 0
        print("OK: PDF export successful and generated non-empty bytes.")
        
        # 8. Test: Guest can export DOCX
        docx_res = client.get(f"/api/v1/reports/{report_id}/export/docx", headers={"Authorization": f"Bearer {guest_token}"})
        assert docx_res.status_code == 200
        assert docx_res.headers["content-type"] == "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        assert len(docx_res.content) > 0
        print("OK: DOCX export successful and generated non-empty bytes.")
        
        # 9. Test: Guest CANNOT delete a report (403)
        del_res = client.delete(f"/api/v1/reports/{report_id}", headers={"Authorization": f"Bearer {guest_token}"})
        assert del_res.status_code == 403
        
        # 10. Test: Admin can delete a report (200)
        del_res = client.delete(f"/api/v1/reports/{report_id}", headers={"Authorization": f"Bearer {admin_token}"})
        assert del_res.status_code == 200
        print("OK: Report successfully deleted by Admin.")
        
    finally:
        Config.DEVELOPMENT_BYPASS_AUTH = old_bypass
        cleanup_test_data(case_id)

if __name__ == "__main__":
    try:
        run_phase4_tests()
        print("\nALL PHASE 4 TESTS PASSED SUCCESSFULLY! OK.")
        sys.exit(0)
    except AssertionError as e:
        print(f"\nTEST FAILURE: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"\nUNEXPECTED EXCEPTION DURING TESTS: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)
